---
all:
  hosts:
    production1:
      ansible_host: localhost
      ansible_user: ubuntu
      ansible_ssh_private_key_file: subspace.pem
      hostname: web1
    gatewood-production:
      ansible_host: 35.85.81.237
      ansible_user: ubuntu
      hostname: gatewood-production
  children:
    production:
      hosts:
        gatewood-production:
    production_web:
      hosts:
        gatewood-production:
    production_worker:
      hosts:
        gatewood-production:
