version: "3"
services:
  rails:
    # Development
    build: rails
    # Production
    # image: ghcr.io/tenforwardconsulting/gatewood-rails:${TAG}
    environment:
      - REDIS_URL=redis://redis:6379/1
      - PORT=3700
      - GATEWOOD_DATABASE_HOST=db
      - RAILS_SERVE_STATIC_ASSETS=1 # TODO configure caddy to do this?
      # configure in .env
      - SECRET_KEY_BASE
      - BASECAMP_CLIENT_ID
      - BASECAMP_CLIENT_SECRET
      - SLACK_TEAM
      - GATEWOOD_HOST
      - GATEWOOD_DATABASE_NAME
      - GATEWOOD_DATABASE_USER
      - GATEWOOD_DATABASE_PASSWORD

    ports:
      - "3000:3000"
    links:
      - redis
      - db

  bolt:
    # Development
    build: bolt
    # Production
    # image: ghcr.io/tenforwardconsulting/gatewood-bolt:${TAG}
    links:
      - rails
    environment:
      # configure in .env
      - SLACK_SIGNING_SECRET
      - SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN

  redis:
    image: redis:latest

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${GATEWOOD_DATABASE_PASSWORD}
      POSTGRES_USER: ${GATEWOOD_DATABASE_USER}
      POSTGRES_DB: ${GATEWOOD_DATABASE_NAME}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    command: "caddy reverse-proxy --from ${GATEWOOD_HOST} --to http://rails:3700"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy-data:/data

