version: "3"
services:
  rails:
    build: rails
    environment:
      - REDIS_URL: "redis://redis:6379/1"
      - PORT: "3000"
      - GATEWOOD_DATABASE_PASSWORD: gatewood
      - GATEWOOD_DATABASE_HOST: db
      # configure in .env
      - BASECAMP_CLIENT_ID
      - BASECAMP_CLIENT_SECRET
      - BASECAMP_TEAM
      - SLACK_TEAM
      - GATEWOOD_HOST
    ports:
      - "3000:3000"
    links:
      - redis
      - db
  bolt:
    build: bolt
    links:
      - rails
    environment:
      # configure in .env
      - SLACK_SIGNING_SECRET
      - SLACK_BOT_TOKEN
      - SLACK_APP_TOKEN

  redis:
    image: redis:latest
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: gatewood
      POSTGRES_USER: gatewood
      POSTGRES_DB: gatewood_production
    volumes:
      ./pg-data:/var/lib/postgresql/data
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    command: "caddy reverse-proxy --from ${GATEWOOD_HOST} --to http://rails:3000"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy-data:/data

